name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    # Runs everyday at 1:00 AM
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator

      - name: Clone BPB workjs
        id: download
        run: |
          wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js || exit 1

      - name: Validate downloaded file
        run: |
          if [ ! -f origin.js ]; then
            echo "Error: origin.js not downloaded successfully."
            exit 1
          fi

      - name: Obfuscate BPB worker js
        id: obfuscate
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 0.5 \
          --dead-code-injection false \
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding 'base64' \
          --transform-object-keys true \
          --unicode-escape-sequence true || exit 1

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet _worker.js; then
            echo "No changes detected in _worker.js"
            echo "::set-output name=has_changes::false"
          else
            echo "Changes detected in _worker.js"
            echo "::set-output name=has_changes::true"
          fi

      - name: Commit changes
        if: steps.changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
